'use client';
import {useState} from 'react';
import {CheckCircle2,ChevronRight,ChevronLeft,Heart,Star,CircleCheck,Brain,LockKeyhole,Code2,Bug,MessageSquare,Keyboard} from 'lucide-react';
import {motion} from 'framer-motion';
import {useStore} from '@/store/useStore';
export default function LessonView({module,onDone}:{module:any;onDone:()=>void}){
 const [index,setIndex]=useState(0),[qIndex,setQIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[wrong,setWrong]=useState(false);
 const lesson=module.lessons[index],questions=lesson.questions||[],q=questions[qIndex],lastLesson=index===module.lessons.length-1,lastQuestion=qIndex===questions.length-1;
 const {hearts,xp,spendHeart}=useStore();
 const choose=(i:number)=>{if(selected!==null)return;setSelected(i);if(i!==q.correctIndex){setWrong(true);spendHeart()}};
 const next=()=>{if(selected===null)return;if(!lastQuestion){setQIndex(x=>x+1);setSelected(null);setWrong(false)}else if(!lastLesson){setIndex(x=>x+1);setQIndex(0);setSelected(null);setWrong(false)}else onDone()};
 return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="min-h-screen bg-[#F7F7F7] pb-8">
  <header className="sticky top-0 z-40 border-b-2 border-[#e5e5e5] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[760px] items-center gap-3 px-4 py-3"><button onClick={onDone} className="rounded-xl p-2 text-[#777]" aria-label="Exit lesson"><ChevronLeft/></button><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase text-[#58CC02]">{module.phase} · Module {module.id}</div><div className="truncate text-sm font-black">{module.title}</div></div><span className="flex items-center gap-1 rounded-xl bg-[#FFF4CC] px-2.5 py-1.5 text-xs font-black text-[#A87800]"><Star size={14} fill="currentColor"/>{xp}</span><span className="flex items-center gap-1 rounded-xl bg-[#FFE8E8] px-2.5 py-1.5 text-xs font-black text-[#D92D2D]"><Heart size={14} fill="currentColor"/>{hearts}</span></div><div className="mx-auto h-2 max-w-[760px] bg-[#E5E5E5]"><motion.div animate={{width:`${((index*questions.length+qIndex+1)/(module.lessons.length*questions.length))*100}%`}} className="h-full bg-[#58CC02]"/></div></header>
  <main className="mx-auto max-w-[650px] px-4 py-6">
   <div className="mb-5 flex items-center gap-2 text-xs font-black uppercase text-[#777]"><span className="rounded-lg bg-[#E5F7FF] px-2 py-1 text-[#0783BA]">Lesson {index+1}/{module.lessons.length}</span><span>Question {qIndex+1}/{questions.length}</span></div>
   <div className="mb-5"><div className="mb-3 flex items-center gap-2"><span className="rounded-xl bg-[#EAF8FF] px-3 py-1.5 text-xs font-black uppercase text-[#0783BA]">{q.type==="mcq"?"Quick check":q.type==="code"?"Code challenge":q.type==="debug"?"Debug challenge":"Scenario challenge"}</span>{q.type==="code"&&<Code2 size={18} className="text-[#0783BA]"/>}{q.type==="debug"&&<Bug size={18} className="text-[#D92D2D]"/>}{q.type==="scenario"&&<MessageSquare size={18} className="text-[#58CC02]"/>}</div><div className="flex items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#58CC02] text-white shadow-[0_4px_0_#46A302]"><Brain/></div><h1 className="text-2xl font-black leading-tight">{q.question}</h1></div></div>
{q.code&&<div className="mb-5 overflow-x-auto rounded-2xl bg-[#202124] p-4 text-sm text-[#D7FBC7] shadow-lg"><div className="mb-2 flex items-center gap-2 text-xs font-black uppercase text-[#9AEF68]"><Keyboard size={14}/>Code to inspect</div><pre className="font-mono leading-6">{q.code}</pre></div>}
   <div className="space-y-3">{q.options.map((option:string,i:number)=>{const correct=selected!==null&&i===q.correctIndex,bad=selected===i&&i!==q.correctIndex;return <motion.button key={option} whileTap={selected===null?{scale:.985}:undefined} onClick={()=>choose(i)} disabled={selected!==null} className={'w-full rounded-2xl border-2 p-4 text-left font-black transition '+(correct?'border-[#58CC02] bg-[#E9F9DF] text-[#358500]':bad?'border-[#FF4B4B] bg-[#FFE8E8] text-[#D92D2D]':'border-[#E5E5E5] bg-white shadow-[0_3px_0_#d5d5d5]')}>{String.fromCharCode(65+i)}. {option}{correct&&<CircleCheck className="float-right"/>}</motion.button>})}</div>
   {selected!==null&&<motion.div initial={{y:10,opacity:0}} animate={{y:0,opacity:1}} className={'mt-5 rounded-2xl p-4 '+(wrong?'bg-[#FFE8E8]':'bg-[#E9F9DF]')}><div className="font-black">{wrong?'Not quite — keep learning!':'Excellent! 🎉'}</div><p className="mt-1 text-sm font-bold leading-6">{q.explanation}</p></motion.div>}
   <div className="mt-6 flex gap-3"><button onClick={onDone} className="quest-btn w-1/3 bg-white text-[#777] shadow-[0_5px_0_#c9c9c9]">Exit</button><button disabled={selected===null} onClick={next} className="quest-btn quest-green flex-1 disabled:cursor-not-allowed disabled:bg-[#bdbdbd] disabled:shadow-[0_5px_0_#999]">{lastQuestion&&lastLesson?<><CheckCircle2 className="mr-2 inline"/>Complete · +{module.xpReward} XP</>:<>Continue <ChevronRight className="ml-1 inline"/></>}</button></div>
   <div className="mt-7 rounded-2xl border-2 border-[#e5e5e5] bg-white p-4"><div className="flex items-center gap-2 text-xs font-black uppercase text-[#777]"><LockKeyhole size={15}/>Learning rule</div><p className="mt-2 text-sm font-bold leading-6 text-[#666]">Get the question right, understand why, then move forward. Wrong answers cost a heart.</p></div>
  </main>
 </motion.div>
}